### ISSUE TITLE
Grandchild etc components

### ISSUE THREAD

**Issue by juniperalcorn** [juniperalcorn/knitwhich#1]
I am struggling with my component hierarchy.

First, to pass data through multiple components.
App>Nav>Dashboard>My patterns
API call is on App, sets state, pass state through other components. Can be accessed on Dashboard but not on My patterns?

And this one just won't show up:
App>Nav>Dashboard>Tools>Measure
Can't get Measure to display on the screen.

**Comment by tara-fenton** [comment]
Can you provide code samples? (use 3 ticks to start and end your end snippet)

**Comment by juniperalcorn** [comment]
I figured it out--I moved all the Route information to App. Thanks!
